# Generated by Django 5.1.4 on 2025-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Main_Post', 'Main_Post'), ('Tendance', 'Tendance'), ('Regular', 'Regular'), ('Category', 'Category'), ('Small_cat', 'Small_cat'), ('Dernier_Post', 'Dernier_Post')], max_length=200),
        ),
    ]
