# Generated by Django 5.1.5 on 2025-03-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_date_alter_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='post_date',
        ),
    ]
