# Generated by Django 5.1.5 on 2025-03-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Tendance', 'Tendance'), ('Category', 'Category'), ('Tendance', 'Tendance'), ('Dernier_Post', 'Dernier_Post')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
