# Generated by Django 5.1.5 on 2025-03-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_post_section_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Main_Post',
            field=models.BooleanField(default=False),
        ),
    ]
