# Generated by Django 5.1.5 on 2025-03-11 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_post_main_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Tendance', 'Tendance'), ('Regular', 'Regular'), ('Category', 'Category'), ('Small_cat', 'Small_cat'), ('Dernier_Post', 'Dernier_Post')], max_length=200),
        ),
    ]
